# Generated by `terraform plan -generate-config-out=generated.tf` against the
# live cluster (id in terraform.tfvars), then cleaned - the raw output is not
# valid as written and mirrors API state rather than intent:
#   - the four GPU plugin/DRA blocks and the RDMA/P2P-registry blocks were all
#     `enabled = false` AND mutually exclusive (device plugin vs DRA driver):
#     the provider rejects them together, and none is wanted here -> removed
#   - `destroy_all_associated_resources`, `kubeconfig_expire_seconds`,
#     `registry_integration` were null (unset) -> removed
#   - `cluster_subnet`, `service_subnet`, `vpc_uuid`, `worker_subnet_uuid`
#     are what DigitalOcean assigned from the default VPC; left computed so
#     the configuration is not tied to one account's network ids
#   - `routing_agent { enabled = false }` and `isolated_workers = false` are
#     the provider defaults -> removed
#   - node_pool: `node_count = 0` (the API reports the autoscaler-managed
#     count as 0 here) -> var.node_count, ignored in plans below; empty
#     `labels`/`tags` and the null `gpu_partition_mode` -> removed
#   - literals -> variables (variables.tf) so the same configuration can adopt
#     or create a cluster with the Doks module's defaults
resource "digitalocean_kubernetes_cluster" "this" {
  name    = var.cluster_name
  region  = var.region
  version = var.kubernetes_version
  tags    = var.tags

  # Control plane: HA (cannot be switched off again), surge upgrades so node
  # replacements never drop below the pool size, no unattended minor upgrades -
  # a version bump is a reviewed change to var.kubernetes_version.
  ha            = true
  surge_upgrade = true
  auto_upgrade  = false

  maintenance_policy {
    day        = var.maintenance_window.day
    start_time = var.maintenance_window.start_time
  }

  # DOKS default; keeps CoreDNS replicas proportional to the node count.
  coredns_autoscaler {
    enabled = true
  }

  node_pool {
    name       = var.node_pool_name
    size       = var.node_size
    node_count = var.node_count
    auto_scale = true
    min_nodes  = var.min_nodes
    max_nodes  = var.max_nodes
  }

  lifecycle {
    # The cluster autoscaler owns the live node count between min and max;
    # `version` moves on its own during automatic patch upgrades in the
    # maintenance window and must not be reverted by the next apply.
    ignore_changes = [
      node_pool[0].node_count,
    ]
  }
}
