{{- with .Values.namespacePolicy.resourceQuota }}
{{- if .enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ $.Release.Name }}-quota
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  hard:
    requests.cpu: {{ .requests.cpu | quote }}
    requests.memory: {{ .requests.memory | quote }}
    limits.cpu: {{ .limits.cpu | quote }}
    limits.memory: {{ .limits.memory | quote }}
    pods: {{ .pods | quote }}
{{- end }}
{{- end }}
